version: '3.8'

services:
  postgres-user:
    image: postgres:16-alpine
    container_name: userdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:16-alpine
    container_name: orderdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

volumes:
  user_data:
  order_data:
